site_name: Tarocco_Matteo

repo_url: https://github.com/TaroccoMatteo/TaroccoMatteo-4BI-2020-2021

nav:
    - 'MD': 'Default.md'

theme:
    name: readthedocs



nav:
    - 'prova': 'index.md'
    - 'alghe': 'Alghe_01.java'
    - 'Asta_01' : 'Asta_01.java'
    - 'Asta_02' : 'Asta_02.java'
    - 'ControlloInput_01' : 'ControlloInput_01.java'
    - 'DepositoBancario_01' : 'DepositoBancario_01.java'
    - 'LavandinoOtturato_01' : 'LavandinoOtturato_01.java'
    - 'NumeroPrimo_01' : 'NumeroPrimo_01.java'
    - 'PaninoPastina_01' : 'PaninoPastina_01.java'
    - 'PariDispari_01' : 'PariDispari_01.java'
    - 'PersoneAmmalate_01' : 'PersoneAmmalate_01.java'
    - 'PersoneAmmalate_02' : 'PersoneAmmalate_02.java'
    - 'PosizioneCifra_01' : 'PosizioneCifra_01.java'
    - 'Quantecifre_01' : 'Quantecifre_01.java'
    - 'SerieNumeri_01' : 'SerieNumeri_01.java'
    - 'SerieNumeri_02' : 'SerieNumeri_02.java'
    - 'SerieNumerica_01' : 'SerieNumerica_01.java'
    - 'SerieNumerica_02' : 'SerieNumerica_02.java'
    - 'mcm_01' : 'mcm_01.java'
    - 'carta': 'Carta.java'
    - 'cartaTest' : 'CartaTest.java'
    
